---
name: Fetch johnvansickle's ffmpeg

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/johnvansickle.yml

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: check if we need to trigger a build
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FULL_VERSION=$(curl https://johnvansickle.com/ffmpeg/git-readme.txt | grep "version:" | awk '{print $2}')
          VERSION=${FULL_VERSION:0:7}
          echo "full_version=$FULL_VERSION" >> "$GITHUB_ENV"
          echo "version=$VERSION" >> "$GITHUB_ENV"
          TODAY=$(date +'%Y-%m-%d')
          echo "date=$TODAY" >> "$GITHUB_ENV"
          if ! wget --spider "https://github.com/${{github.repository}}/releases/download/$VERSION/ffmpeg" > /dev/null 2>&1; then
          echo "trigger=true" >> "$GITHUB_ENV"
          echo "Build $VERSION"
          else
          echo "trigger=false" >> "$GITHUB_ENV"
          echo "Skip $VERSION"
          fi
          if [ -z $VERSION ]; then
          echo "trigger=false" >> "$GITHUB_ENV"
          echo "No version found"
          fi


      - name: build
        if: env.trigger == 'true'
        env:
          VERSION: ${{ env.version }}
        run: |
          mkdir tmp
          curl -sSLf -o tmp/ffmpeg.tar.xz "https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz"
          tar -xvf tmp/ffmpeg.tar.xz -C tmp --strip-components=1
          mv tmp/ffmpeg .
          mv tmp/ffprobe .

      - name: release
        if: env.trigger == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FULL_VERSION: ${{ env.full_version }}
          VERSION: ${{ env.version }}
          TODAY: ${{ env.date }}
        run: |
          gh release create "${VERSION}" --notes "Version: ${FULL_VERSION}<br>Date: ${TODAY}" --title "FFmpeg-${FULL_VERSION}" --repo "${{github.repository}}" || true
          gh release upload "${VERSION}" "ffmpeg" --clobber --repo "${{github.repository}}"
          gh release upload "${VERSION}" "ffprobe" --clobber --repo "${{github.repository}}"

          gh release create "latest"  --notes "Version: ${FULL_VERSION}<br>Date: ${TODAY}" --title "FFmpeg" --repo "${{github.repository}}" || true
          gh release edit "latest"  --notes "Version: ${FULL_VERSION}<br>Date: ${TODAY}" --title "FFmpeg" --repo "${{github.repository}}" || true
          gh release upload "latest" "ffmpeg" --clobber --repo "${{github.repository}}"
          gh release upload "latest" "ffprobe" --clobber --repo "${{github.repository}}"

          # generate Dockerfile
          echo "FROM scratch" > Dockerfile
          echo "COPY ffmpeg /ffmpeg" >> Dockerfile
          echo "COPY ffprobe /ffprobe" >> Dockerfile

      - name: Set up QEMU
        if: env.trigger == 'true'
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        if: env.trigger == 'true'
        uses: docker/setup-buildx-action@master

      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build
        if: env.trigger == 'true'
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.version }}
            ghcr.io/${{ github.repository }}:${{ env.date }}
