---
name: Fetch official's ffmpeg

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/official.yml
  schedule:
    - cron: 0 4 * * *

permissions: write-all
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: build
        run: |
          mkdir tmp
          curl -sSLf -o tmp/ffmpeg.tar.xz "https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz"
          tar -xvf tmp/ffmpeg.tar.xz -C tmp --strip-components=1
          mv tmp/bin/ffmpeg .
          mv tmp/bin/ffprobe .
          TODAY=$(date +'%Y-%m-%d')
          echo "date=$TODAY" >> "$GITHUB_ENV"

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODAY: ${{ env.date }}
        run: |
          gh release create "${TODAY}" --notes "Arch: Linux x86_64" --title "FFmpeg-${TODAY}" --repo "${{github.repository}}" || true
          gh release upload "${TODAY}" "ffmpeg" --clobber --repo "${{github.repository}}"
          gh release upload "${TODAY}" "ffprobe" --clobber --repo "${{github.repository}}"

          gh release create "latest"  --notes "Date: ${TODAY}<br>Arch: Linux x86_64" --title "FFmpeg" --repo "${{github.repository}}" || true
          gh release edit "latest"  --notes "Date: ${TODAY}<br>Arch: Linux x86_64" --title "FFmpeg" --repo "${{github.repository}}" || true
          gh release upload "latest" "ffmpeg" --clobber --repo "${{github.repository}}"
          gh release upload "latest" "ffprobe" --clobber --repo "${{github.repository}}"

          # generate Dockerfile
          echo "FROM scratch" > Dockerfile
          echo "COPY ffmpeg /ffmpeg" >> Dockerfile
          echo "COPY ffprobe /ffprobe" >> Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GHCR
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.version }}
            ghcr.io/${{ github.repository }}:${{ env.date }}

  # https://github.com/liskin/gh-workflow-keepalive
  keepalive:
    if: github.event_name == 'schedule'
    name: Keepalive
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Re-enable workflow
        run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
          "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
          *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          echo "Re-enable $workflow"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"
